spring:
    datasource:
        url: jdbc:mysql://localhost:3306/msa_step02_order?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# RestTemplate이 참조하는 설정값
# 서비스 디스커버리 설정(localhost:8081 대신 payment-service라는 이름으로 결제서비스를 탐색)
# payment-service의 이름은 spring.application.name을 기반으로 함
service:
    payment:
        url: http://payment-service/payments

server:
    port: 8080
